{"level":"info","msg":"Wrapper started","pid":270,"time":"2021-10-25T09:25:52.453Z","wrapper":270}
{"level":"info","msg":"finding gitaly","pid":270,"pid_file":"/var/opt/gitlab/gitaly/gitaly.pid","time":"2021-10-25T09:25:52.453Z","wrapper":270}
{"level":"info","msg":"spawning a process","pid":270,"time":"2021-10-25T09:25:52.461Z","wrapper":270}
{"gitaly":285,"level":"info","msg":"monitoring gitaly","pid":270,"time":"2021-10-25T09:25:52.462Z","wrapper":270}
time="2021-10-25T09:25:53Z" level=info msg="Starting GitalyversionGitaly, version 14.4.0"
time="2021-10-25T09:25:53Z" level=warning msg="git path not configured. Using default path resolution" resolvedPath=/opt/gitlab/embedded/bin/git
{"latencies":[0.001,0.005,0.025,0.1,0.5,1,10,30,60,300,1500],"level":"info","msg":"grpc prometheus histograms enabled","time":"2021-10-25T09:25:53.099Z"}
{"level":"info","msg":"License database preloaded","time":"2021-10-25T09:26:00.500Z"}
{"level":"info","msg":"clearing disk cache object folder","storage":"default","time":"2021-10-25T09:26:00.504Z"}
{"level":"info","msg":"moving disk cache object folder to /var/opt/gitlab/git-data/repositories/+gitaly/tmp/diskcache3815055858","storage":"default","time":"2021-10-25T09:26:00.511Z"}
{"level":"info","msg":"disk cache object folder doesn't exist, no need to remove","storage":"default","time":"2021-10-25T09:26:00.515Z"}
{"level":"info","msg":"Starting file walker for /var/opt/gitlab/git-data/repositories/+gitaly/cache","path":"/var/opt/gitlab/git-data/repositories/+gitaly/cache","time":"2021-10-25T09:26:00.515Z"}
{"level":"info","msg":"Starting file walker for /var/opt/gitlab/git-data/repositories/+gitaly/state","path":"/var/opt/gitlab/git-data/repositories/+gitaly/state","time":"2021-10-25T09:26:00.515Z"}
{"level":"info","msg":"finished tempdir cleaner walk","storage":"default","time":"2021-10-25T09:26:00.517Z","time_ms":14}
{"level":"info","msg":"cleared all cache object files in /var/opt/gitlab/git-data/repositories/+gitaly/tmp/diskcache3815055858 after 6.625ms","storage":"default","time":"2021-10-25T09:26:00.522Z"}
{"level":"info","msg":"starting RSS monitor","supervisor.name":"gitaly-ruby.1","supervisor.rss_threshold":209715200,"time":"2021-10-25T09:26:01.935Z"}
{"level":"info","msg":"starting RSS monitor","supervisor.name":"gitaly-ruby.0","supervisor.rss_threshold":209715200,"time":"2021-10-25T09:26:01.934Z"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.1 /var/opt/gitlab/gitaly/internal_sockets/ruby.1 \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.1: connect: connection refused\". Reconnecting...","pid":285,"system":"system","time":"2021-10-25T09:26:01.941Z"}
{"level":"warning","msg":"spawned","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.0"],"supervisor.name":"gitaly-ruby.0","supervisor.pid":399,"time":"2021-10-25T09:26:01.942Z"}
{"level":"warning","msg":"spawned","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","supervisor.pid":401,"time":"2021-10-25T09:26:01.949Z"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.0 /var/opt/gitlab/gitaly/internal_sockets/ruby.0 \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.0: connect: connection refused\". Reconnecting...","pid":285,"system":"system","time":"2021-10-25T09:26:01.986Z"}
{"address":"/var/opt/gitlab/gitaly/gitaly.socket","level":"info","msg":"listening at unix address","time":"2021-10-25T09:26:02.087Z"}
{"address":"/var/opt/gitlab/gitaly/internal_sockets/internal_285.sock","level":"info","msg":"listening at unix address","time":"2021-10-25T09:26:02.104Z"}
{"address":"localhost:9236","level":"info","msg":"starting prometheus listener","time":"2021-10-25T09:26:02.142Z"}
{"level":"info","msg":"maintenance: daily scheduled","pid":285,"scheduled":"2021-10-25T12:00:00Z","time":"2021-10-25T09:26:02.143Z"}
{"level":"info","msg":"PID 401 BUNDLE_GEMFILE=/opt/gitlab/embedded/service/gitaly-ruby/Gemfile","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2021-10-25T09:26:03.591Z"}
{"level":"info","msg":"PID 399 BUNDLE_GEMFILE=/opt/gitlab/embedded/service/gitaly-ruby/Gemfile","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.0"],"supervisor.name":"gitaly-ruby.0","time":"2021-10-25T09:26:03.828Z"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.0 /var/opt/gitlab/gitaly/internal_sockets/ruby.0 \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.0: operation was canceled\". Reconnecting...","pid":285,"system":"system","time":"2021-10-25T09:28:57.780Z"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.1 /var/opt/gitlab/gitaly/internal_sockets/ruby.1 \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.1: i/o timeout\". Reconnecting...","pid":285,"system":"system","time":"2021-10-25T09:35:11.014Z"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {unix:/var/opt/gitlab/gitaly/internal_sockets/internal_285.sock localhost \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/internal_285.sock: i/o timeout\". Reconnecting...","pid":285,"system":"system","time":"2021-10-25T09:35:11.023Z"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:35:11.031Z","worker.name":"gitaly-ruby.0"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.0 /var/opt/gitlab/gitaly/internal_sockets/ruby.0 \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.0: i/o timeout\". Reconnecting...","pid":285,"system":"system","time":"2021-10-25T09:35:11.036Z"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:35:11.036Z","worker.name":"gitaly-ruby.1"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:35:30.743Z","worker.name":"gitaly-ruby.0"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:35:30.798Z","worker.name":"gitaly-ruby.1"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:37:59.507Z","worker.name":"gitaly-ruby.0"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:37:59.522Z","worker.name":"gitaly-ruby.1"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:42:09.250Z","worker.name":"gitaly-ruby.0"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.0 /var/opt/gitlab/gitaly/internal_sockets/ruby.0 \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.0: operation was canceled\". Reconnecting...","pid":285,"system":"system","time":"2021-10-25T09:42:09.427Z"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:42:10.073Z","worker.name":"gitaly-ruby.1"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:42:27.751Z","worker.name":"gitaly-ruby.0"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:42:35.419Z","worker.name":"gitaly-ruby.1"}
{"error":"rpc error: code = DeadlineExceeded desc = Deadline Exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:42:47.354Z","worker.name":"gitaly-ruby.0"}
{"error":"rpc error: code = DeadlineExceeded desc = Deadline Exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:42:52.883Z","worker.name":"gitaly-ruby.1"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:43:03.393Z","worker.name":"gitaly-ruby.0"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:43:16.234Z","worker.name":"gitaly-ruby.1"}
{"level":"info","msg":"removed gitaly-ruby worker from balancer due to sustained failing health checks","time":"2021-10-25T09:43:21.889Z","worker.name":"gitaly-ruby.1","worker.pid":401}
{"level":"info","msg":"sending SIGTERM","time":"2021-10-25T09:44:53.363Z","worker.name":"gitaly-ruby.1","worker.pid":401}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:45:18.266Z","worker.name":"gitaly-ruby.0"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {unix:/var/opt/gitlab/gitaly/internal_sockets/internal_285.sock localhost \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/internal_285.sock: i/o timeout\". Reconnecting...","pid":285,"system":"system","time":"2021-10-25T09:45:22.920Z"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:45:22.939Z","worker.name":"gitaly-ruby.1"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.1 /var/opt/gitlab/gitaly/internal_sockets/ruby.1 \u003cnil\u003e 0 \u003cnil\u003e}: didn't receive server preface in time. Reconnecting...","pid":285,"system":"system","time":"2021-10-25T09:44:35.964Z"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:45:23.869Z","worker.name":"gitaly-ruby.0"}
{"level":"info","msg":"I, [2021-10-25T09:26:10.362102 #401]  INFO -- sentry: ** [Raven] Raven 3.0.4 configured not to capture errors: DSN not set","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2021-10-25T09:45:31.078Z"}
{"level":"info","msg":"GRPC-RUBY: WARN: Using gitaly-proto 14.4.0","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2021-10-25T09:45:31.089Z"}
{"level":"info","msg":"GRPC-RUBY: WARN: failed call: #\u003cGRPC::ActiveCall:0x00007f19480097a0\u003e","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2021-10-25T09:45:31.090Z"}
{"level":"info","msg":"call#run_batch failed somehow","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2021-10-25T09:45:31.090Z"}
{"level":"info","msg":"GRPC-RUBY: WARN: failed call: #\u003cGRPC::ActiveCall:0x00007f196002e7b8\u003e","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2021-10-25T09:45:31.090Z"}
{"level":"info","msg":"call#run_batch failed somehow","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2021-10-25T09:45:31.090Z"}
{"level":"info","msg":"GRPC-RUBY: WARN: failed call: #\u003cGRPC::ActiveCall:0x00007f1910012860\u003e","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2021-10-25T09:45:31.090Z"}
{"level":"info","msg":"call#run_batch failed somehow","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2021-10-25T09:45:31.090Z"}
{"error":null,"level":"warning","msg":"exited","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2021-10-25T09:45:32.054Z"}
{"level":"warning","msg":"spawned","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","supervisor.pid":847,"time":"2021-10-25T09:45:32.079Z"}
{"level":"info","msg":"PID 847 BUNDLE_GEMFILE=/opt/gitlab/embedded/service/gitaly-ruby/Gemfile","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","285","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2021-10-25T09:45:35.059Z"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.1 /var/opt/gitlab/gitaly/internal_sockets/ruby.1 \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.1: connect: no such file or directory\". Reconnecting...","pid":285,"system":"system","time":"2021-10-25T09:45:37.809Z"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.1 /var/opt/gitlab/gitaly/internal_sockets/ruby.1 \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.1: connect: no such file or directory\". Reconnecting...","pid":285,"system":"system","time":"2021-10-25T09:45:53.745Z"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-10-25T09:45:54.949Z","worker.name":"gitaly-ruby.0"}
